name = "DistributedImageReconstruction"
uuid = "b99085f1-2f43-45a7-bd38-d511f4bff3b1"
authors = ["nHackel <nHackel@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
